### ISSUE TITLE
timeReceived is before exchange publish time

### ISSUE THREAD

**Issue by woonsangcho** [crypto-chassis/ccapi_cpp#39]
To replicate the issue, we can try running `market_data_simple` in one of the examples.

1. In *ccapi_session_options.h*, Initialize to 1.
`long warnLateEventMaxMilliSeconds{1};  // used to print a warning log message if an event arrives late`
2. Enable `CCAPI_ENABLE_LOG_WARN`
3. Extend Logger class to simply `std:cout << ... `
4. Remove condition `wsMessage.recapType == MarketDataMessage::RecapType::NONE` in *ccapi_market_data_service.h:470*
    This condition is assuming timeReceived is always after the message publish time from the exchange. However, often it is not the case. Notice that `timeReceived` is before `wsMessage.tp`, even after local machine time sync. This issue is easily seen if you flip the condition to `std::chrono::duration_cast<std::chrono::milliseconds>(timeReceived - wsMessage.tp).count() < -this->sessionOptions.warnLateEventMaxMilliSeconds`.

On a different matter, this example is simply streaming live market data. Was there a reason why  `wsMessage.recapType` is SOLICITED rather than NONE? It can also be classified into a normal tick data as you commented inline, or changing the condition to include SOLICITED would be a workaround.

Thanks!

**Comment by cryptochassis** [comment]
@woonsangcho Thank you for the feedback. Following the steps that you provided, I was able to see the problem (at least on Coinbase which is the exchange that I tried). Based on preliminary investigation, it seems to be a Coinbase server time issue. Here are two things that I noticed:
1. Enable CCAPI_ENABLE_LOG_DEBUG. This way we could see the raw messages received from Coinbase: 
`0x700009e05000: [2021-01-17T04:39:52.522214000Z] {ccapi_market_data_service.h:341} DEBUG        received a text message: {"type":"l2update","product_id":"BTC-USD","changes":[["sell","36142.70","0.00000000"]],"time":"2021-01-17T04:39:52.526806Z"}
0x700009e05000: [2021-01-17T04:39:52.522277000Z] {ccapi_market_data_service.h:405} WARN        late websocket message: timeReceived = (1610858392,522142000), wsMessage.tp = (1610858392,526806000), wsConnection `
The `timeReceived` value ultimately came from https://github.com/crypto-chassis/ccapi_cpp/blob/v2.2.8/include/ccapi_cpp/service/ccapi_market_data_service.h#L328. It seems that Coinbase's server does sometimes have time skew.
2. Coinbase provides an rest endpoint to probe their server time: https://docs.pro.coinbase.com/#time. So using this and trying a couple of times, we could indeed observe something like this: `1610858537.2
{"iso":"2021-01-17T04:42:17.621Z","epoch":1610858537.621}
1610858537.411317` using this script `python -c 'import time; print time.time()' && curl https://api.pro.coinbase.com/time && python3 -c 'import time; print(time.time())'`. We can see that for this moment Coinbase's server clock was slightly behind ours.
Let us know if you think the root cause isn't the problem from Coinbase's server but rather it is something else.

**Comment by cryptochassis** [comment]
@woonsangcho 

> On a different matter, this example is simply streaming live market data. Was there a reason why wsMessage.recapType is SOLICITED rather than NONE? It can also be classified into a normal tick data as you commented inline, or changing the condition to include SOLICITED would be a workaround.

Sorry if it looks confusing. We are trying to follow Bloomberg's convention: blpapi_cpp_3.13.1.1, in fact the inline comments were directly copied from their open-source library's inline comments. To put it straightforward, for our library a recap=`SOLICITED` message for now only exists in market depth websocket stream and it is always the first message providing a snapshot when we initially subscribed to the exchange. For coinbase, it corresponds to their level2 channel and their message type "snapshot" (https://docs.pro.coinbase.com/#the-level2-channel). But indeed the timestamp might be somewhat confusing because their "snapshot" message doesn't provide a timestamp (though some other exchanges do) and we left it blank (i.e. it became unix zero timestamp) for Coinbase. So we'll make a fix to make sure that the timestamp for a `SOLICITED` message is well-defined for all the exchanges that we support.

**Comment by woonsangcho** [comment]
@cryptochassis Thank you for taking your time looking into this, and I appreciate your detailed feedback. I agree with you that the issue is on Coinbase's end.
